title: Testing Long Haul
description: Testing the long haul theme

url: https://prahladyeri.github.io/test-long-haul
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: prahladyeri
    twitter: prahladyeri
    email: prahladyeri@yahoo.com
    linkedin: prahlad-yeri-243a5316
